version: "3"
services:
  postgres:
    image: postgres:14.2
    container_name: "postgres"
    env_file: 
      - .env
    ports:
      - ${POSTGRES_LOCAL_PORT}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # удали/закомментируй меня после первого запуска
  airflow-initdb:
    image: antttoni/lab05:${TAG}
    depends_on:
        postgres:
            condition: service_healthy
    env_file: 
      - .env
    command:
      - -c
      - airflow users list || (airflow db init )
    entrypoint: /bin/bash

  redis:
      image: redis:7.0.0
      restart: always
      ports:
        - ${REDIS_PORT}:6379
      command: redis-server --save 20 1 --loglevel warning
      volumes: 
        - ./data/redis:/var/lib/redis/data

  airflow-webserver:
    image: antttoni/lab05:${TAG}
    restart: always
    depends_on:
        postgres:
            condition: service_healthy
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs_webserver:/usr/local/airflow/logs
    ports:
      - "${AIRFLOW_LOCAL_PORT}:8080"
    env_file: 
      - .env
    entrypoint: airflow webserver

  airflow-scheduler:
    image: antttoni/lab05:${TAG}
    restart: always
    depends_on:
        postgres:
            condition: service_healthy
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs_scheduler:/usr/local/airflow/logs
    entrypoint: airflow scheduler