version: "3"
services:
  postgres:
    image: postgres:14.2
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # удали/закомментируй меня после первого запуска
  airflow-initdb:
    image: antttoni/lab05:0.0.1
    depends_on:
        postgres:
            condition: service_healthy
    entrypoint: airflow db init

  redis:
      image: redis:7.0.0
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --save 20 1 --loglevel warning
      volumes: 
        - ./data/redis:/var/lib/redis/data

  airflow-webserver:
    image: antttoni/lab05:0.0.1
    restart: always
    depends_on:
        postgres:
            condition: service_healthy
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs_webserver:/usr/local/airflow/logs
    ports:
      - "8085:8080"
    entrypoint: airflow webserver

  airflow-scheduler:
    image: antttoni/lab05:0.0.1
    restart: always
    depends_on:
        postgres:
            condition: service_healthy
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs_scheduler:/usr/local/airflow/logs
    entrypoint: airflow scheduler