name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  LAB05_IMAGE: antttoni/lab05 
  VERSION: 0.0.8

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ANTON_DOLGIKH_DOCKER_USER_LAB05 }}
          password: ${{ secrets.ANTON_DOLGIKH_DOCKER_LAB05 }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ANTON_DOLGIKH_LAB05 }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.LAB05_IMAGE }}:${{ env.VERSION }}

