name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE="antttoni/lab05"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: "antttoni"
          password: ${{ secrets.ANTON_DOLGIKH_LAB05 }}
          
      - name: "Build&Deploy template-server"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/prod-template-server:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/prod-template-server:latest
          secrets: |
            "ASPNETCORE_ENVIRONMENT=Release"
          build-args: |
            build_mode=Release
