name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          TAG=0.0.5
          IMAGE="antttoni/lab05"
          echo ::set-output name=tagged_image::${IMAGE}:${TAG}
          echo ::set-output name=tag::${TAG}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ANTON_DOLGIKH_DOCKER_USER_LAB05 }}
          password: ${{ secrets.ANTON_DOLGIKH_DOCKER_LAB05 }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/antttoni/lab05:0.0.5
          username: ${{ secrets.ANTON_DOLGIKH_DOCKER_USER_LAB05 }}
          password: ${{ secrets.ANTON_DOLGIKH_DOCKER_LAB05 }}





