name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    	- name: Test1
    	  run:  |
		echo ${{ env.LAB05_IMAGE }}:${{ env.MAJOR_VERSION }}${{ env.PATCH_VERSION }}


      - name: Autoincrement a new patch version
        run: |
          echo "NEW_PATCH_VERSION=$((${{ env.PATCH_VERSION }}+1))" >> $GITHUB_ENV

    	- name: Test2
    	  run:  |
		echo $NEW_PATCH_VERSION
		echo ${{ env.LAB05_IMAGE }}:${{ env.MAJOR_VERSION }}${{ env.PATCH_VERSION }}

      - name: Update patch version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'PATCH_VERSION'
          value: ${{ env.NEW_PATCH_VERSION }}
          repository: ${{ github.repository }}
          token: ${{ secrets.ANTON_DOLGIKH_LAB05 }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ANTON_DOLGIKH_DOCKER_USER_LAB05 }}
          password: ${{ secrets.ANTON_DOLGIKH_DOCKER_LAB05 }}

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ANTON_DOLGIKH_LAB05 }}


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.LAB05_IMAGE }}:${{ env.MAJOR_VERSION }}${{ env.PATCH_VERSION }}





