name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

  - uses: mr-smithers-excellent/docker-build-push@v5
    name: Build & push Docker image
    with:
      image: antttoni/lab05
      tags: 0.0.6
      registry: docker.io
          username: ${{ secrets.ANTON_DOLGIKH_DOCKER_USER_LAB05 }}
          password: ${{ secrets.ANTON_DOLGIKH_DOCKER_LAB05 }}






